---
name: Continuous Integration

on:
    pull_request:
    push:
        branches:
            - '*'
            - '*/*'
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 1

            - name: Run Docker container
              run: docker compose up -d

            - name: Build ROS Package
              run: |
                  source ./.env
                  docker exec "$CONTAINER_NAME" /bin/zsh -c "source /opt/ros/noetic/setup.zsh && catkin build"
              shell: /usr/bin/bash -e {0}
